name: CI to Docker hub
env:
  REGISTRY: leopoldodonnell
  CLI_VERSION: 1.11.0

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Setup up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        build-args: |
          CLI_VERSION=${{ env.CLI_VERSION }}
        tags: ${{ env.REGISTRY }}/structurizr-cli:v${{ env.CLI_VERSION }}
